In [3]:
#this implementation of PCA doesnot use the standard scalers provided by the sklearn library
import numpy as np
from numpy import mean

In [19]:
#mean centering the given matrix
X = np.array([[7,4,3],[4,1,8],[6,3,5],[8,6,1],[8,5,7],[7,2,9],[5,3,3],[9,5,8],[7,4,5],[8,2,2]])

col_mean = mean(X,axis=0)
x_std = X-col_mean
cov = x_std.T.dot(x_std)
print(cov)

[[ 20.9  14.5  -3.9]
 [ 14.5  22.5 -11.5]
 [ -3.9 -11.5  70.9]]


In [31]:
#finding eigen values and vectors for the covariance matrix
eig_val, eig_vect = np.linalg.eig(cov)
print(eig_val)
print(eig_vect)
eig_var = np.var(eig_vect, axis=0)
print(eig_var)
eig_vect = eig_vect/eig_var
print(eig_vect)

[ 6.74935338 33.0851634  74.46548322]
[[-0.70172743  0.69903712 -0.1375708 ]
 [ 0.70745703  0.66088917 -0.25045969]
 [ 0.08416157  0.27307986  0.95830278]]
[0.33243551 0.03703232 0.29719883]
[[-2.11086785 18.87640424 -0.46289145]
 [ 2.12810308 17.84627853 -0.84273441]
 [ 0.2531666   7.37409453  3.22445001]]


In [44]:
#forming the eigen value and eigen vector pair
eig_pairs = [(eig_val[i],eig_vect[:,i])for i in range(len(eig_val))]

eig_pairs.sort(reverse = True)
print(eig_pairs)
print()
#to throw out a single feature which is the one with eigen value = 6
arr = []
for i in range(len(eig_pairs)-1):
    arr.append(eig_pairs[i][1])
    
x = np.asarray(arr).T
print(x)
print("Principal components")
print(cov.dot(x))

[(74.46548322367073, array([-0.46289145, -0.84273441,  3.22445001])), (33.085163401176004, array([18.87640424, 17.84627853,  7.37409453])), (6.74935337515323, array([-2.11086785,  2.12810308,  0.2531666 ]))]

[[-0.46289145 18.87640424]
 [-0.84273441 17.84627853]
 [ 3.22445001  7.37409453]]
Principal components
[[-34.46943526 624.52891866]
 [-62.75462535 590.44704139]
 [240.1102278  243.97312242]]


In [48]:
from sklearn.decomposition import PCA
import numpy as np

X = np.array([[7,4,3],[4,1,8],[6,3,5],[8,6,1],[8,5,7],[7,2,9],[5,3,3],[9,5,8],[7,4,5],[8,2,2]])
pca = PCA(2)
pca = pca.fit(X)
print(pca.components_)
print(pca.explained_variance_)

[[ 0.1375708   0.25045969 -0.95830278]
 [ 0.69903712  0.66088917  0.27307986]]
[8.27394258 3.67612927]
